// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // CLI/マイグレーションは接続数の少ない直接接続(DIRECT_URL)を使う。
  // pgbouncerのトランザクションプーリング接続(DATABASE_URL)はprepared statementを
  // 使うマイグレーションと相性が悪いため、実行時(src/lib/prisma.ts)とは別の接続文字列にしている。
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
